import Head from 'next/head'
import { Inter } from 'next/font/google'
import axios from 'axios';

import styles from '@/styles/Home.module.css'
import { Button, ButtonGroup, Flex, Stack,Box, Text, Badge, Image } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps(context) {
  let res = await axios.get('https://www.themealdb.com/api/json/v1/1/random.php');
  let data = res.data;
  console.log(data);
  return {props:{data}}
}

export default function Home({data}) {
  console.log(data.meals)
  let meals = data.meals;
  return (
    <>
      <Head>
        <title>Recettes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex justifyContent={'center'}>
        <Flex flexDirection={'column'} w='80%'>
          {
            meals.map((meal) => {
              return (
                <>
                  <Box mt={10}>
                    <Text as="h1" fontSize={'xl'}>{meal.strMeal}</Text>
                    {meal.strTags != null && meal.strTags.split(',').map((tag) => {
                      return (
                        <>
                        <Badge>{tag}</Badge>
                        </>
                      )})}
                    <Image src={`${meal.strMealThumb}`} width='300px'></Image>
                  </Box>
                  <Box mt={5} mb={5}>
                    <Text as="h2" fontSize={'sm'}>
                      {meal.strInstructions}
                    </Text>
                  </Box>
                </>
              )
            }
          )}
        </Flex>
      </Flex>
    </>
  )
}


